[build]
base = "."
command = "pip install -r requirements-netlify.txt && python -m uvicorn asr_main:app --reload"
functions = "functions"
publish = "."

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200