[build]
command = "echo 'Current directory:' && pwd && echo 'Full directory structure:' && find . -type f -name '*.py' && echo 'Functions directory:' && ls -la functions/ && echo 'ASR.py file details:' && ls -la functions/asr.py && echo 'File content preview:' && head -10 functions/asr.py"
publish = ""
functions = "functions"

[build.environment]
PIP_VERSION = "23.3.1"
PYTHON_VERSION = "3.12"
PIP_REQUIREMENTS = "requirements.txt"

[functions]
included_files = [
    "functions/*.py",
    "functions/static_ffmpeg/**"
]