[build]
publish = ""
functions = "functions"

[build.environment]
PIP_VERSION = "23.3.1"
PYTHON_VERSION = "3.12"
PIP_REQUIREMENTS = "requirements.txt"

[functions]
included_files = [
    "netlify/functions/**/*.py",
    "netlify/functions/**/static_ffmpeg/**"
]