[build]
command = "pip install -r requirements-netlify.txt && python -m uvicorn asr_main:app --host 0.0.0.0 --port 8080"
functions = "functions"
publish = "."

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200