[build]
command = "echo 'Current directory:' && pwd && echo 'Listing project structure:' && find . -name '*.py' -o -name 'netlify' -type d && echo 'Functions directory contents:' && ls -la netlify/functions/ && echo 'ASR directory contents:' && ls -la netlify/functions/asr/"
publish = ""
functions = "netlify/functions"

[build.environment]
PIP_VERSION = "23.3.1"
PYTHON_VERSION = "3.12"
PIP_REQUIREMENTS = "requirements.txt"

[functions]
included_files = [
    "netlify/functions/**/*.py",
    "netlify/functions/**/static_ffmpeg/**"
]